/*
 * EN: Brand-slug → simple-icons mark map. These car brands ship a CC0 vector mark
 *     in the simple-icons package, so we render them as inline, infinitely-scalable
 *     SVG (via nm-brand-icon) instead of a bitmap file. Slugs match brands.json ids.
 *     Brands absent here fall back to an uploaded PNG (MediaService.getBrandLogoUrl)
 *     and, failing that, to the BrandLogoComponent initials tile.
 * RU: Карта «слаг марки → значок simple-icons». Для этих марок в пакете simple-icons
 *     есть векторный знак (CC0), поэтому рисуем их встроенным масштабируемым SVG
 *     (через nm-brand-icon), а не растровым файлом. Слаги совпадают с id из brands.json.
 *     Отсутствующие здесь марки берут загруженный PNG (MediaService.getBrandLogoUrl),
 *     а при его отсутствии — плитку с инициалами BrandLogoComponent.
 */
import type { BrandIcon } from '@shared/components/brand-icon/brand-icon.component';
import {
  siAcura,
  siAudi,
  siBmw,
  siCadillac,
  siChevrolet,
  siChrysler,
  siCitroen,
  siDacia,
  siDaf,
  siDsautomobiles,
  siFerrari,
  siFiat,
  siFord,
  siHonda,
  siHyundai,
  siInfiniti,
  siIveco,
  siJeep,
  siKia,
  siLada,
  siLamborghini,
  siMan,
  siMaserati,
  siMazda,
  siMg,
  siMini,
  siMitsubishi,
  siNissan,
  siOpel,
  siPeugeot,
  siPorsche,
  siRenault,
  siScania,
  siSeat,
  siSkoda,
  siSmart,
  siSubaru,
  siSuzuki,
  siTesla,
  siToyota,
  siVolkswagen,
  siVolvo,
} from 'simple-icons';

/** Brand id (brands.json) → simple-icons mark, for brands with a bundled vector logo. */
export const BRAND_SIMPLE_ICONS: Readonly<Record<string, BrandIcon>> = {
  acura: siAcura,
  audi: siAudi,
  bmw: siBmw,
  cadillac: siCadillac,
  chevrolet: siChevrolet,
  chrysler: siChrysler,
  citroen: siCitroen,
  dacia: siDacia,
  daf: siDaf,
  ds: siDsautomobiles,
  ferrari: siFerrari,
  fiat: siFiat,
  ford: siFord,
  honda: siHonda,
  hyundai: siHyundai,
  infiniti: siInfiniti,
  iveco: siIveco,
  jeep: siJeep,
  kia: siKia,
  lamborghini: siLamborghini,
  man: siMan,
  maserati: siMaserati,
  mazda: siMazda,
  mg: siMg,
  mini: siMini,
  mitsubishi: siMitsubishi,
  nissan: siNissan,
  opel: siOpel,
  peugeot: siPeugeot,
  porsche: siPorsche,
  renault: siRenault,
  scania: siScania,
  seat: siSeat,
  skoda: siSkoda,
  smart: siSmart,
  subaru: siSubaru,
  suzuki: siSuzuki,
  tesla: siTesla,
  toyota: siToyota,
  volkswagen: siVolkswagen,
  volvo: siVolvo,
  // ВАЗ / Lada share the AvtoVAZ mark.
  vaz: siLada,
  'vaz-lada': siLada,
};
